export { default as Home } from './Home'
export { default as Room } from './Room'
export { default as Ranking } from './Ranking'
export { default as Score } from './Score'
export { default as NoMatch } from './NoMatch'